#This script produces the numerical integration for the EoMs
#generated by three_link_pendulum.py

from three_link_pendulum import l, m, M, Ixx, Iyy, Izz, g, kane
from scipy.integrate import odeint
from code_gen import numeric_right_hand_side
from numpy import radians, linspace, hstack, zeros, ones

params = list(l) + list(m) + list(M) + list(Ixx) + list(Iyy) + list(Izz) + [g]

param_vals = [10.0 for x in l] + [5.0 for x in m] + [10.0 for x in M] + \
    [5.0 for x in list(Ixx) + list(Iyy) + list(Izz)] + [9.8]

print("Generating numeric right hand side.")
right_hand_side = numeric_right_hand_side(kane, params)

print("Integrating equations of motion.")

t = linspace(0.0, 10.0, num=1000)
x0 = hstack((ones(6) * radians(10.0), zeros(6)))
states = odeint(right_hand_side, x0, t, args=(param_vals,))

print("Integration done.")
